import { ArrowRight, ArrowUpRight, Check } from "lucide-react";
import { Link } from "wouter";

const principles = ["Start with the smallest useful thing.", "Make the interface quieter than the idea.", "Leave people with more agency, not less."];

export default function About() {
  return <div className="about-page"><section className="page-intro about-intro"><div className="container page-intro-inner"><div><p className="eyebrow"><span className="eyebrow-line" />About the studio</p><h1>Thoughtful tools<br /><em>for real life.</em></h1></div><p className="page-intro-note">Amir Digital is a small independent<br />studio making useful things on purpose.</p></div></section><section className="about-story section-pad"><div className="container about-story-grid"><div className="about-poster"><div className="poster-circle" /><span>AMIR<br />DIGITAL</span><strong>MAKE<br /><i>SPACE.</i></strong><small>EST. 2026 / ONLINE</small></div><div className="about-copy"><p className="eyebrow"><span className="eyebrow-line" />The short version</p><h2>Small products.<br /><em>Long usefulness.</em></h2><p>Amir Digital is a one-person studio for digital products that respect your time, your attention, and the work you are trying to do. I make books, software, websites, and little apps that help good ideas become tangible.</p><p>This is a quiet corner of the internet for practical thinking, clear interfaces, and the occasional unreasonable belief that the best tool might be the one you actually look forward to opening.</p><Link href="/products" className="text-link">See the product shelf <ArrowRight size={15} /></Link></div></div></section><section className="principles-section"><div className="container principles-inner"><div><p className="eyebrow light-eyebrow"><span className="eyebrow-line" />How I work</p><h2>Less, but<br /><em>better chosen.</em></h2></div><div className="principles-list">{principles.map((principle, index) => <div className="principle" key={principle}><span>0{index + 1}</span><p>{principle}</p><Check size={17} /></div>)}</div></div></section><section className="about-cta section-pad"><div className="container about-cta-inner"><div><p className="eyebrow"><span className="eyebrow-line" />Have a question?</p><h2>Let’s make room<br /><em>for a good idea.</em></h2></div><Link href="/contact" className="button button-dark">Get in touch <ArrowUpRight size={16} /></Link></div></section></div>;
}


