import { ArrowUpRight, Heart, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { CheckoutButton } from "@/components/CheckoutButton";
import { ProductVisual } from "@/components/SiteLayout";
import { trpc } from "@/lib/trpc";
import { formatProductPrice, productVisual } from "@/lib/catalog";

export default function ChildrenRoom() {
  const productsQuery = trpc.products.list.useQuery();
  const storyProducts = (productsQuery.data ?? []).filter(product => product.format === "story");
  if (productsQuery.isLoading) return <div className="empty-state"><p>Loading products...</p></div>;
  if (productsQuery.isError) return <div className="empty-state"><p>Products are temporarily unavailable. Please try again.</p></div>;
  return <div className="children-page"><section className="children-hero"><div className="container children-hero-inner"><div><p className="eyebrow children-eyebrow"><span className="eyebrow-line" />The children’s room</p><h1>Small stories.<br /><em>Big worlds.</em></h1><p>Illustrated books and gentle stories for curious young minds — designed to be shared with a trusted grown-up.</p><div className="children-hero-actions"><Link href="/children/game" className="button button-primary children-game-cta">Play the games <ArrowUpRight size={16} /></Link><Link href="/games" className="text-link">Open Games <ArrowUpRight size={15} /></Link></div></div><div className="children-sun" aria-hidden="true"><Sparkles size={24} /><span>read<br />kindly</span></div></div></section><section className="children-intro section-pad"><div className="container children-intro-grid"><div><p className="eyebrow"><span className="eyebrow-line" />For families</p><h2>Made for little<br /><em>discoveries.</em></h2></div><div className="children-intro-copy"><p>A quiet shelf of illustrated books and stories with clear age guidance, read-aloud moments, and invitations for conversation.</p><div className="children-promises"><span><ShieldCheck size={17} />Parent-friendly</span><span><Heart size={17} />Thoughtful stories</span><span><Sparkles size={17} />Ages clearly marked</span></div></div></div></section><section className="children-products section-pad"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span className="eyebrow-line" />The story shelf</p><h2>Read a little<br /><em>adventure.</em></h2></div><Link href="/games" className="text-link">Visit Games <ArrowUpRight size={15} /></Link></div><div className="children-grid">{storyProducts.map(product => { const visual = productVisual(product); return <article className="children-card" key={product.slug}><Link href={`/products/${product.slug}`} className="children-card-visual"><ProductVisual {...visual} compact /><span className="children-card-icon">{product.icon}</span></Link><div className="children-card-body"><div className="children-card-meta"><span>{product.ageRange}</span><span>{formatProductPrice(product)}</span></div><h3>{product.name}</h3><p>{product.description}</p><div className="children-card-actions"><Link href={`/products/${product.slug}`} className="text-link">See details <ArrowUpRight size={14} /></Link><CheckoutButton product={product}>Buy now</CheckoutButton></div></div></article>; })}</div></div></section><section className="children-note"><div className="container"><p className="eyebrow children-eyebrow"><span className="eyebrow-line" />A note for grown-ups</p><p>These digital stories are intended for use with an adult’s judgment about screen time, context, and each child’s needs.</p></div></section></div>;
}



