import { useState } from "react";
import { ArrowUpRight, Mail, MapPin } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

export default function Contact() {
  const [sent, setSent] = useState(false);
  const contact = trpc.marketing.contact.useMutation({ onSuccess: () => { setSent(true); toast.success("Message received. I’ll be in touch soon."); }, onError: () => toast.error("We couldn't send that just now. Please try again.") });
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); contact.mutate({ name: String(form.get("name") ?? ""), email: String(form.get("email") ?? ""), topic: String(form.get("topic") ?? ""), message: String(form.get("message") ?? "") }); event.currentTarget.reset(); };
  return <div className="contact-page"><section className="page-intro contact-intro"><div className="container page-intro-inner"><div><p className="eyebrow"><span className="eyebrow-line" />Say hello</p><h1>What’s on<br /><em>your mind?</em></h1></div><p className="page-intro-note">Questions about a product, a project,<br />or just want to share a good link?</p></div></section><section className="contact-section section-pad"><div className="container contact-grid"><div className="contact-aside"><p className="eyebrow"><span className="eyebrow-line" />The inbox</p><h2>Good conversations<br /><em>start small.</em></h2><p>Tell me what you’re working on, what you’re curious about, or where the current tool is getting in the way. I read every note.</p><div className="contact-details"><a href="mailto:hello@amir.digital"><Mail size={17} /><span><small>Email</small>hello@amir.digital</span></a><div><MapPin size={17} /><span><small>Based in</small>London · working globally</span></div></div></div><form className="contact-form" onSubmit={handleSubmit}><div className="form-row"><label>Name<input name="name" required placeholder="Your name" disabled={contact.isPending} /></label><label>Email<input name="email" required type="email" placeholder="you@example.com" disabled={contact.isPending} /></label></div><label>What can I help with?<select name="topic" defaultValue="product" disabled={contact.isPending}><option value="product">A product question</option><option value="project">A project idea</option><option value="hello">Just saying hello</option></select></label><label>Your message<textarea name="message" rows={6} required placeholder="A few words is plenty..." disabled={contact.isPending} /></label><button className="button button-dark" type="submit" disabled={contact.isPending}>{sent ? "Message sent" : contact.isPending ? "Sending…" : "Send message"} <ArrowUpRight size={16} /></button><p className="form-note">I usually reply within two working days.</p></form></div></section></div>;
}


