import { useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Mail, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { ProductVisual } from "@/components/SiteLayout";
import { CheckoutButton } from "@/components/CheckoutButton";
import { posts } from "@/lib/products";
import { trpc } from "@/lib/trpc";
import { formatProductPrice, productVisual } from "@/lib/catalog";
import { toast } from "sonner";

export default function Home() {
  const [email, setEmail] = useState("");
  const subscribe = trpc.marketing.subscribe.useMutation({ onSuccess: () => { toast.success("Bienvenue dans la newsletter Amir Digital."); setEmail(""); }, onError: () => toast.error("Impossible de vous inscrire pour le moment.") });
  const featuredQuery = trpc.products.getFeatured.useQuery();
  const productsQuery = trpc.products.list.useQuery();
  const categoriesQuery = trpc.categories.list.useQuery();
  const featured = featuredQuery.data?.[0];
  const categories = (categoriesQuery.data ?? []).map(category => ({ ...category, count: (productsQuery.data ?? []).filter(product => product.category === category.name).length.toString().padStart(2, "0") }));
  const handleSignup = (event: React.FormEvent) => { event.preventDefault(); if (!email || !email.includes("@")) { toast.error("Veuillez saisir une adresse email valide."); return; } subscribe.mutate({ email }); };

  if (featuredQuery.isLoading || productsQuery.isLoading || categoriesQuery.isLoading) return <div className="empty-state"><p>Chargement de la boutique…</p></div>;
  if (featuredQuery.isError || productsQuery.isError || categoriesQuery.isError || !featured) return <div className="empty-state"><p>La boutique est momentanément indisponible.</p></div>;
  const featuredVisual = productVisual(featured);

  return <>
    <section className="hero-section"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line" />Studio digital tunisien</p><h1>Le digital<br /><em>qui vous aide.</em></h1><p className="hero-lede">Logiciels, sites web, ressources open source et livres pour apprendre l’informatique — conçus avec simplicité, depuis la Tunisie.</p><div className="hero-actions"><Link href="/products" className="button button-primary">Découvrir la boutique <ArrowUpRight size={16} /></Link><a href="#services" className="text-link">Voir nos solutions <ArrowDown size={15} /></a></div><div className="hero-proof"><div className="avatars"><span>TN</span><span>FR</span><span>EN</span><span>+</span></div><p><strong>Des produits utiles, accessibles</strong><br />pour apprendre, créer et avancer.</p></div></div><div className="hero-art" aria-label="Illustration de produits digitaux"><div className="art-note">Un studio<br /><span>indépendant</span><br />sur internet.</div><div className="art-ring" /><div className="art-card art-card-orange"><span>01 / OFFRE</span><strong>APPRENDRE<br />&amp; CRÉER</strong><small>des outils qui<br />restent humains</small></div><div className="art-card art-card-paper"><span>AMIR DIGITAL / TN</span><strong>Moins<br />de bruit.<br /><i>Plus d’impact.</i></strong><small>Logiciels · web · open source</small></div><div className="art-scribble">↗</div><div className="art-caption"><span className="caption-dot" />Fait en Tunisie · pensé pour tous</div></div></div></section>
    <section className="ticker" aria-label="Nos engagements"><div className="ticker-track"><span>APPRENDRE EN FAISANT.</span><i>✦</i><span>DES OUTILS QUI SERVENT.</span><i>✦</i><span>OUVERT, SIMPLE, HUMAIN.</span><i>✦</i><span>APPRENDRE EN FAISANT.</span><i>✦</i><span>DES OUTILS QUI SERVENT.</span></div></section>
    <section id="services" className="services-strip section-pad"><div className="container"><div className="section-heading compact-heading"><div><p className="eyebrow"><span className="eyebrow-line" />Ce que nous construisons</p><h2>Une idée claire,<br /><em>un vrai résultat.</em></h2></div><p className="section-note">Des solutions digitales<br />pour chaque étape de votre projet.</p></div><div className="service-grid"><div><span>01</span><Sparkles size={18} /><h3>Logiciels &amp; apps</h3><p>Des outils web et desktop simples, pensés pour gagner du temps.</p></div><div><span>02</span><ArrowUpRight size={18} /><h3>Sites web</h3><p>Une présence en ligne crédible, rapide et adaptée à votre activité.</p></div><div><span>03</span><Check size={18} /><h3>Open source &amp; livres</h3><p>Des ressources accessibles pour les étudiants, les enfants et les curieux.</p></div></div></div></section>
    <section id="featured" className="featured-section section-pad"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span className="eyebrow-line" />Produit à la une</p><h2>Commencez par<br /><em>une bonne ressource.</em></h2></div><Link href="/products" className="text-link">Voir tous les produits <ArrowRight size={15} /></Link></div><div className="featured-card"><div className="featured-visual"><ProductVisual {...featuredVisual} /></div><div className="featured-details"><div className="product-meta"><span className="pill">{featured.category}</span><span>Nouveau · 2026</span></div><h3>{featured.name}</h3><p>{featured.description}</p><ul className="feature-list">{featured.features.map(feature => <li key={feature}><Check size={15} />{feature}</li>)}</ul><div className="price-row"><div><strong>{formatProductPrice(featured)}</strong><span>{featured.priceNote}</span></div><CheckoutButton product={featured} className="button button-dark">Acheter maintenant</CheckoutButton></div><Link href={`/products/${featured.slug}`} className="subtle-link">Voir les détails <ArrowRight size={14} /></Link></div></div></div></section>
    <section className="category-section section-pad"><div className="container"><div className="section-heading compact-heading"><div><p className="eyebrow"><span className="eyebrow-line" />La boutique</p><h2>Choisissez votre<br /><em>point de départ.</em></h2></div><p className="section-note">Pas de catalogue interminable.<br />Seulement des choses utiles.</p></div><div className="category-grid">{categories.map((category, index) => <Link key={category.name} href={`/products?category=${category.name}`} className={`category-card category-${index + 1}`}><span className="category-count">{category.count}</span><div><h3>{category.name}</h3><p>{category.description}</p></div><ArrowUpRight size={18} /></Link>)}</div></div></section>
    <section id="notes" className="notes-section section-pad"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span className="eyebrow-line" />Le carnet Amir</p><h2>Apprendre, créer,<br /><em>partager.</em></h2></div><Link href="/about" className="text-link">Découvrir Amir Digital <ArrowRight size={15} /></Link></div><div className="notes-grid">{posts.map((post, index) => <article className={`note-card note-${index + 1}`} key={post.slug}><div className="note-top"><span>{post.category}</span><span>{post.readTime}</span></div><Link href={`/notes/${post.slug}`}><h3>{post.title}</h3></Link><p>{post.excerpt}</p><Link href={`/notes/${post.slug}`} className="circle-arrow" aria-label={`Lire ${post.title}`}><ArrowUpRight size={17} /></Link><div className="note-date">{post.date}</div></article>)}</div></div></section>
    <section className="newsletter-section"><div className="container newsletter-inner"><div><p className="eyebrow light-eyebrow"><span className="eyebrow-line" />Une bonne idée, de temps en temps</p><h2>Faites de la place<br /><em>pour la suite.</em></h2><p className="newsletter-copy">Recevez les nouveaux logiciels, ressources gratuites et notes pratiques d’Amir Digital. Pas de spam, seulement du concret.</p></div><form className="signup-form" onSubmit={handleSignup}><label htmlFor="newsletter-email">Votre adresse email</label><div className="input-wrap"><Mail size={17} /><input id="newsletter-email" type="email" placeholder="vous@exemple.com" value={email} onChange={(event) => setEmail(event.target.value)} disabled={subscribe.isPending} /><button type="submit" aria-label="S’inscrire" disabled={subscribe.isPending}><ArrowUpRight size={18} /></button></div><p>Gratuit. Désinscription en un clic.</p></form></div></section>
  </>;
}
