import { useState } from "react";
import { Link, useLocation } from "wouter";
import { useCart } from "@/contexts/CartContext";
import { ArrowUpRight, Instagram, Linkedin, Menu, X } from "lucide-react";

const navItems = [
  { label: "Boutique", href: "/products" },
  { label: "Sur mesure", href: "/buy" },
  { label: "Enfants", href: "/children" },
  { label: "À propos", href: "/about" },
  { label: "Carnet", href: "/#notes" },
  { label: "Contact", href: "/contact" },
];

export function ProductVisual({ type, accent, accentSoft, compact = false }: { type: "book" | "dashboard" | "browser" | "phone"; accent: string; accentSoft: string; compact?: boolean }) {
  if (type === "book") return <div className={`visual visual-book ${compact ? "visual-compact" : ""}`} style={{ ["--accent" as string]: accent, ["--accent-soft" as string]: accentSoft }} aria-hidden="true"><div className="book-shadow" /><div className="book-cover"><span className="book-kicker">AMIR DIGITAL · TN</span><span className="book-symbol">✦</span><strong>Apprendre<br />l’informatique<br />autrement</strong><span className="book-caption">Une ressource claire pour progresser.</span></div></div>;
  if (type === "dashboard") return <div className={`visual visual-dashboard ${compact ? "visual-compact" : ""}`} style={{ ["--accent" as string]: accent, ["--accent-soft" as string]: accentSoft }} aria-hidden="true"><div className="dash-window"><div className="dash-top"><i /><i /><i /><span>amir digital / projet</span></div><div className="dash-body"><div className="dash-sidebar"><b>Projet<br />Clair</b><em /><em /><em /><em /></div><div className="dash-content"><small>AUJOURD’HUI</small><strong>Construire la<br />prochaine étape.</strong><div className="dash-line" /><div className="dash-cards"><i /><i /><i /></div></div></div></div></div>;
  if (type === "browser") return <div className={`visual visual-browser ${compact ? "visual-compact" : ""}`} style={{ ["--accent" as string]: accent, ["--accent-soft" as string]: accentSoft }} aria-hidden="true"><div className="browser-window"><div className="browser-bar"><i /><i /><i /><span>votre-site.tn</span></div><div className="browser-page"><small>AMIR DIGITAL STUDIO</small><strong>Une présence<br />qui compte.</strong><div className="browser-button">Découvrir <ArrowUpRight size={12} /></div><div className="browser-block" /></div></div></div>;
  return <div className={`visual visual-phone ${compact ? "visual-compact" : ""}`} style={{ ["--accent" as string]: accent, ["--accent-soft" as string]: accentSoft }} aria-hidden="true"><div className="phone-shell"><div className="phone-speaker" /><div className="phone-screen"><small>AMIR DIGITAL · LUN 04</small><strong>Un peu<br />chaque jour.</strong><div className="habit-row"><span>Lire 10 pages</span><b>✓</b></div><div className="habit-row"><span>Créer une idée</span><b>✓</b></div><div className="habit-row muted"><span>Partager</span><b>+</b></div></div></div></div>;
}

export function SiteLayout({ children }: { children: React.ReactNode }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [location] = useLocation();
  const { itemCount } = useCart();
  const closeMenu = () => setMenuOpen(false);
  return <div className="site-shell"><div className="announcement"><span>Nouveau : ressources digitales pensées depuis la Tunisie</span><Link href="/products">Voir la boutique <ArrowUpRight size={14} /></Link></div><header className="site-header"><div className="container nav-wrap"><Link href="/" className="brand" onClick={closeMenu} aria-label="Amir Digital accueil"><span className="brand-mark">A</span><span>amir<span className="brand-dot">.</span>digital</span></Link><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Fermer le menu" : "Ouvrir le menu"} aria-expanded={menuOpen}>{menuOpen ? <X size={21} /> : <Menu size={21} />}</button><nav className={`main-nav ${menuOpen ? "is-open" : ""}`} aria-label="Navigation principale">{navItems.map(item => <Link key={item.href} href={item.href} onClick={closeMenu} className={location === item.href ? "active" : ""}>{item.label}</Link>)}<Link href="/cart" className="nav-cta" onClick={closeMenu}>Panier ({itemCount}) <ArrowUpRight size={15} /></Link></nav></div></header><main>{children}</main><footer className="site-footer"><div className="container footer-grid"><div><Link href="/" className="brand footer-brand"><span className="brand-mark">A</span><span>amir<span className="brand-dot">.</span>digital</span></Link><p className="footer-copy">Des produits digitaux utiles pour apprendre, créer et faire avancer vos projets.</p><div className="socials"><a href="https://linkedin.com" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={17} /></a><a href="https://twitter.com" target="_blank" rel="noreferrer" aria-label="X"><span className="x-icon">𝕏</span></a><a href="https://instagram.com" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={17} /></a></div></div><div className="footer-links"><div><span className="footer-label">Explorer</span><Link href="/products">Tous les produits</Link><Link href="/buy">Solutions sur mesure</Link><Link href="/children">Espace enfants</Link><Link href="/about">À propos</Link><Link href="/#notes">Carnet</Link></div><div><span className="footer-label">Échanger</span><a href="mailto:hello@amir.digital">hello@amir.digital</a><Link href="/signup">Newsletter</Link><Link href="/contact">Formulaire de contact</Link><span className="footer-small">Réponse généralement sous 48h.</span></div></div></div><div className="container footer-bottom"><span>© 2026 Amir Digital · Fait en Tunisie</span><span>Paiement sécurisé via Stripe</span></div></footer></div>;
}
